Handle error when tar fails in launch script (#155)

diff --git a/static/launch b/static/launch
--- a/static/launch
+++ b/static/launch
@@ -37,5 +37,13 @@ esac
 
 url="https://github.com/zellij-org/zellij/releases/latest/download/zellij-$arch-$sys.tar.gz"
 curl --location "$url" | tar -C "$dir" -xz
+if [[ $? -ne 0 ]]
+then
+    echo
+    echo "Extracting binary failed, cannot launch zellij :("
+    echo "One probable cause is that a new release just happened and the binary is currently building."
+    echo "Maybe try again later? :)"
+    exit 1
+fi
 "$dir/zellij" "$@"
 exit
